CREATE EXTENSION IF NOT EXISTS btree_gist;

CREATE TABLE IF NOT EXISTS study_rooms (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(50) NOT NULL UNIQUE,
    room_type VARCHAR(20) NOT NULL,
    min_capacity INTEGER NOT NULL,
    max_capacity INTEGER NOT NULL,
    open_time TIME NOT NULL DEFAULT '06:00',
    close_time TIME NOT NULL DEFAULT '23:00',
    active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT chk_study_rooms_capacity
        CHECK (min_capacity > 0 AND max_capacity >= min_capacity),
    CONSTRAINT chk_study_rooms_operating_time
        CHECK (open_time < close_time)
);

COMMENT ON TABLE study_rooms IS
    '스터디룸의 이름, 타입, 수용 인원, 운영 시간과 사용 여부를 관리한다.';

CREATE TABLE IF NOT EXISTS reservations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    study_room_id BIGINT NOT NULL REFERENCES study_rooms (id),
    guest_name VARCHAR(50) NOT NULL,
    guest_email VARCHAR(255) NOT NULL,
    guest_phone VARCHAR(20) NOT NULL,
    start_at TIMESTAMP NOT NULL,
    end_at TIMESTAMP NOT NULL,
    purpose VARCHAR(50) NOT NULL,
    status VARCHAR(20) NOT NULL DEFAULT 'CONFIRMED',
    canceled_at TIMESTAMP,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT chk_reservations_time CHECK (start_at < end_at),
    CONSTRAINT chk_reservations_purpose
        CHECK (char_length(purpose) BETWEEN 1 AND 50),
    CONSTRAINT chk_reservations_status
        CHECK (status IN ('CONFIRMED', 'CANCELED'))
);

COMMENT ON TABLE reservations IS
    '비회원 예약자 정보, 예약 시간, 이용 목적과 예약 상태를 관리한다.';

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1
        FROM pg_constraint
        WHERE conname = 'ex_reservations_no_overlap'
          AND conrelid = 'reservations'::regclass
    ) THEN
        ALTER TABLE reservations
        ADD CONSTRAINT ex_reservations_no_overlap
        EXCLUDE USING gist (
            study_room_id WITH =,
            tsrange(start_at, end_at, '[)') WITH &&
        )
        WHERE (status = 'CONFIRMED');
    END IF;
END $$;

CREATE INDEX IF NOT EXISTS idx_reservations_room_status_start
    ON reservations (study_room_id, status, start_at);

COMMENT ON INDEX idx_reservations_room_status_start IS
    '특정 스터디룸의 확정된 예약 시간을 빠르게 조회한다.';

CREATE INDEX IF NOT EXISTS idx_reservations_guest_lookup
    ON reservations (guest_email, guest_phone, created_at DESC);

COMMENT ON INDEX idx_reservations_guest_lookup IS
    '이메일과 전화번호로 비회원 예약 내역을 최신 순으로 조회한다.';
